[project]
name = "discord-music"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cachier>=4.1.0",
    "discord-py[voice]>=2.6.4",
    "hikari>=2.5.0",
    "loguru>=0.7.3",
    "yt-dlp>=2025.12.8",
]
